apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/hello-world
  creationTimestamp: null
  name: hello-world.apps.local.20250116.1928.30737
spec:
  refName: hello-world.apps.local
  releasedAt: "2025-01-16T19:30:18Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: harbor-dev.buildservice.dev/ci/containerapp-hello-world@sha256:a254d6d118643c109c69c6951f176aec99ac7f773d72a456c7df9ea70ed158d9
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20250116.1928.30737
