apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/hello-world-other-one
  creationTimestamp: null
  name: hello-world-other-one
spec:
  packageRef:
    refName: hello-world-other-one.apps.local
    versionSelection:
      constraints: 20250116.2027.51196
  serviceAccountName: carvel-package-installer
  values:
  - secretRef:
      name: hello-world-other-one-values
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
